### ISSUE TITLE
Bi-directional Conversion

### ISSUE THREAD

**Issue by tomchapin** [jonyluke/Undertale-save-converter#1]
Hello! Just wanted to let you know that I was inspired by this project and I did a full re-write from the ground up. The version I made supports full bi-directional conversion between PC and Switch game saves:

https://github.com/tomchapin/undertale-save-converter

**Comment by jonyluke** [comment]
I had already added it once, but I made a mess and deleted the repository (without knowing that I did not have copies) and I had to do it again, I was working on this feature again, in fact I just added it now
